Repository puppetlabs/puppetlabs-tomcat, pull requests merged in 2018-12, with the labels that each got.

#328 (MODULES-8147) - Add SLES 15 support
  metadata.json
  spec/spec_helper_acceptance.rb
Labels: feature

#329 pdksync - pdksync_heads/master-0-gbf720df
  .gitattributes
  .pdkignore
  .puppet-lint.rc
  .travis.yml
  Rakefile
  metadata.json
  spec/default_facts.yml
  spec/spec_helper.rb
Labels: maintenance

#330 pdksync - (FM-7655) Fix rubygems-update for ruby < 2.3
  .travis.yml
  metadata.json
Labels: bugfix
