Repository puppetlabs/puppetlabs-tomcat, pull requests merged in 2019-04, with the labels that each got.

#344 (MODULES-8817) - Update to account for loss of SVN Tomcat archive
  spec/acceptance/acceptance_1b_spec.rb
  spec/acceptance/acceptance_3b_spec.rb
  spec/spec_helper_acceptance.rb
Labels: bugfix

#347 pdksync - (MODULES-8444) - Raise lower Puppet bound
  metadata.json
Labels: backwards-incompatible

#348 pdksync - (maint) Update pdk-template to f778803
  .gitignore
  .pdkignore
  .puppet-lint.rc
  .travis.yml
  metadata.json
Labels: maintenance
