Repository puppetlabs/puppetlabs-tomcat, pull requests merged in 2019-11, with the labels that each got.

#369 (FM-8275) Add vagrant provision list
  provision.yaml
Labels: maintenance

#373 Fix failing acceptance tests
  .travis.yml
  metadata.json
  provision.yaml
  spec/spec_helper_acceptance_local.rb
Labels: backwards-incompatible

#372 pdksync - (FM-8634) ensure encrypted communication for fixtures
  .fixtures.yml
Labels: maintenance

#374 (FM-8699) - Addition of Support for CentOS 8
  metadata.json
  provision.yaml
Labels: feature

#375 (MODULES-10120) enable simplecov; update to PDK 1.14.1; minor cleanups
  .gitignore
  .pdkignore
  .project
  .rubocop.yml
  .sync.yml
  .travis.yml
  Gemfile
  metadata.json
  spec/default_facts.yml
Labels: maintenance
