Repository puppetlabs/puppetlabs-tomcat, pull requests merged in 2019-06, with the labels that each got.

#356 pdksync - MODULES-9057 Fix the module contribution guide link
  README.md
Labels: maintenance

#354 FM-8050 - add redhat8 support
  metadata.json
Labels: feature

#357 pdksync - pdksync_heads/master-0-g7827fc2
  .rubocop.yml
  .travis.yml
  .vscode/extensions.json
  Gemfile
  Rakefile
  metadata.json
  spec/spec_helper.rb
Labels: maintenance

#322 add show diff to all augeas calls
  manifests/config/context.pp
  manifests/config/context/environment.pp
  manifests/config/context/manager.pp
  manifests/config/context/resource.pp
  manifests/config/context/resourcelink.pp
  manifests/config/context/valve.pp
  manifests/config/server.pp
  manifests/config/server/connector.pp
  manifests/config/server/context.pp
  manifests/config/server/engine.pp
  manifests/config/server/globalnamingresource.pp
  manifests/config/server/host.pp
  manifests/config/server/listener.pp
  manifests/config/server/realm.pp
  manifests/config/server/service.pp
  manifests/config/server/tomcat_users.pp
  manifests/config/server/valve.pp
Labels: needs-rebase, needs-tests
