Repository puppetlabs/puppetlabs-tomcat, pull requests merged in 2020-11, with the labels that each got.

#416 (IAC-1214) - Move SKIP_GCC to test file
  spec/acceptance/acceptance_1b_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: bugfix

#417 (IAC-1236) Adding SLES OSs for release_checks
  provision.yaml
Labels: bugfix

#418 pdksync - Update pdk-templates for gitpod and codespaces support
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .gitpod.Dockerfile
  .gitpod.yml
  .pdkignore
  .rubocop.yml
  .sync.yml
  Gemfile
  data/common.yaml
  hiera.yaml
  metadata.json
Labels: maintenance

#415 Refactor valve types
  manifests/config/context/valve.pp
  manifests/config/server/valve.pp
  spec/acceptance/acceptance_1b_spec.rb
  spec/acceptance/acceptance_3b_spec.rb
  spec/acceptance/acceptance_4b_spec.rb
  spec/acceptance/readme_spec.rb
  spec/defines/config/context/valve_spec.rb
  spec/defines/config/server/connector_spec.rb
  spec/defines/config/server/valve_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: backwards-incompatible

#420 pdksync - (maint) Add release_checks_7 config to provision.yaml
  provision.yaml
Labels: maintenance
