Repository puppetlabs/puppetlabs-tomcat, pull requests merged in 2021-07, with the labels that each got.

#457 Fix nightly as tomcat7 is EOL
  spec/acceptance/acceptance_2b_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: maintenance

#460 Update Tomcat acceptance testing urls
  spec/spec_helper_acceptance_local.rb
Labels: maintenance

#456 (MODULES-9520) Allow removal of webapps
  manifests/install.pp
  spec/acceptance/acceptance_1_readme_spec.rb
Labels: feature

#462 pdksync - (maint) - Updating Contribution Guidelines
  CONTRIBUTING.md
Labels: maintenance

#459 [IAC-1690] - Remove tomcat7 as is EOL
  README.md
  examples/instance_with_context.pp
  examples/instance_with_listener.pp
  examples/instance_with_role_and_user.pp
  readmes/README_ja_JP.md
  spec/acceptance/acceptance_1_readme_spec.rb
  spec/acceptance/acceptance_2b_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: backwards-incompatible

#454 Accept Datatype Sensitive for Secrets
  .puppet-lint.rc
  .sync.yml
  manifests/config/server/tomcat_users.pp
Labels: feature

#463 Release mergeback version 6.0.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance
