Repository puppetlabs/puppetlabs-tomcat, pull requests merged in 2021-05, with the labels that each got.

#446 Add service_name parameter to tomcat::instance
  manifests/instance.pp
  spec/defines/instance_spec.rb
Labels: feature

#443 (MODULES-10644) Document source upgrade process
  README.md
Labels: bugfix

#448 (maint) - PDK update
  .github/workflows/release.yml
  .pdkignore
  .sync.yml
  Gemfile
  metadata.json
  spec/spec_helper.rb
Labels: maintenance
