Repository puppetlabs/puppetlabs-tomcat, pull requests merged in 2022-10, with the labels that each got.

#496 pdksync - (CONT-130) - Dropping Support for Debian 9
  metadata.json
Labels: bugfix, hacktoberfest

#498 pdksync - (PDKSync) Removal of puppet_module_gems
  .devcontainer/README.md
  Gemfile
  metadata.json
Labels: maintenance, hacktoberfest

#500 pdksync - (CONT-189) Remove support for RedHat6 / OracleLinux6 / Scientific6
  metadata.json
Labels: bugfix, hacktoberfest

#501 Exclude name in resources
  manifests/config/context/resources.pp
  spec/defines/config/context/resources_spec.rb
Labels: community
