Repository puppetlabs/puppetlabs-tomcat, pull requests merged in 2022-08, with the labels that each got.

#492 pdksync - (GH-cat-12) Add Support for Redhat 9
  metadata.json
  spec/acceptance/acceptance_1b_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: feature, attention-needed

#493 pdksync - (GH-cat-11) Certify Support for Ubuntu 22.04
  metadata.json
Labels: feature

#491 Allow usage of Context/Resources
  manifests/config/context/resources.pp
  spec/defines/config/context/resources_spec.rb
Labels: feature, community
