Repository puppetlabs/puppetlabs-tomcat, pull requests merged in 2023-07, with the labels that each got.

#538 (CONT-1187) - Fixing module dependency
  metadata.json
Labels: maintenance

#540 pdksync - (CONT-1219) - fail ci for puppetlabs members if no label
  .github/workflows/labeller.yml
Labels: maintenance

#541 CONT-1149-erb_to_epp_conversion_tomcat
  manifests/service.pp
  templates/jsvc-init.epp
Labels: feature

#536 Update var types
  REFERENCE.md
  manifests/config/server/connector.pp
  manifests/config/server/context.pp
  manifests/config/server/engine.pp
  manifests/config/server/globalnamingresource.pp
  manifests/config/server/host.pp
  manifests/config/server/listener.pp
  manifests/config/server/realm.pp
  manifests/config/server/resources.pp
  manifests/config/server/service.pp
  manifests/config/server/valve.pp
  spec/acceptance/acceptance_1b_spec.rb
  spec/acceptance/acceptance_3b_spec.rb
  spec/defines/config/server/connector_spec.rb
Labels: bugfix, community
